fixup! rust: drm: ioctl: Add DRM ioctl abstraction
use code::ERANGE to avoid type confusion with u32.
Fixes following error in drivers/gpu/drm/asahi/driver.rs:57

| error[E0599]: no method named `to_errno` found for type `u32` in the current scope

Signed-off-by: Janne Grunau <j@jannau.net>
(cherry picked from commit f70c52d8a73d48c2fd8cc96cec99d22b12ff3496 https://github.com/AsahiLinux/linux)
Signed-off-by: John Cabaj <john.cabaj@canonical.com>